### ISSUE TITLE
Create function to draw grid

### ISSUE THREAD

**Issue by lrezza** [lrezza/kfolke-lrezza-project#3]

**Comment by ghost** [comment]
Description:
SKAPA FUNKTION

origo: övre vänster hörner

input: 20x10 matris av ints (0-7)
return: -
Funktion: rita grid
rita upp en spelplansgrid av 20x10 squares.

**Comment by klarafolke** [comment]
Det var alltså jag som skrev ghost-grejen innan jag upptäckte att jag hade två accounts och raderade den ena av de :))
